const ActionType = {
    SET_AUTH_USER: 'SET_AUTH_USER',
    UNSET_AUTH_USER: 'UNSET_AUTH_USER',
    SET_IS_PRELOAD: 'SET_IS_PRELOAD',
    RECEIVE_USERS: 'RECEIVE_USERS',
    RECEIVE_TALKS: 'RECEIVE_TALKS',
    ADD_TALK: 'ADD_TALK',
    TOGGLE_LIKE_TALK: 'TOGGLE_LIKE_TALK',
    RECEIVE_TALK_DETAIL: 'RECEIVE_TALK_DETAIL',
    CLEAR_TALK_DETAIL: 'CLEAR_TALK_DETAIL',
    TOGGLE_LIKE_TALK_DETAIL: 'TOGGLE_LIKE_TALK_DETAIL',
};

export default ActionType;
